---
- name: Install Docker on all nodes
  hosts: all
  become: yes
  tasks:
    - name: Install required packages
      package:
        name:
          - docker
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

- name: Create Dockerfile on master node
  hosts: master
  become: yes
  tasks:
    - name: Create Dockerfile that prints "Hello Java"
      copy:
        dest: /home/ansible/Dockerfile
        content: |
          FROM openjdk:8-jdk-alpine
          CMD ["echo", "Hello Java"]

- name: Copy Dockerfile from master to worker node
  hosts: worker
  become: yes
  tasks:
    - name: Fetch Dockerfile from master
      fetch:
        src: /home/ansible/Dockerfile
        dest: /tmp/Dockerfile
        flat: yes
      delegate_to: master

    - name: Copy Dockerfile to worker
      copy:
        src: /tmp/Dockerfile
        dest: /home/ansible/Dockerfile
        remote_src: yes

- name: Build and run Docker image on worker
  hosts: worker
  become: yes
  tasks:
    - name: Build Docker image from Dockerfile
      command: docker build -t hello-java /home/ansible

    - name: Run Docker container to print "Hello Java"
      command: docker run hello-java
